# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: 
  vmImage: ubuntu-latest

steps:
# - task: TerraformTaskV2@2
#   inputs:
#     provider: 'azurerm'
#     command: 'init'
#     backendServiceArm: 'youtube-app-service-connection'
#     backendAzureRmResourceGroupName: 'Lab-RG'
#     backendAzureRmStorageAccountName: 'kubestorage001'
#     backendAzureRmContainerName: 'kubecontainer'
#     backendAzureRmKey: 'terraform.tfstate'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'youtube-app-service-connection'
    allowTelemetryCollection: false

# - task: TerraformTaskV2@2
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     environmentServiceNameAzureRM: 'youtube-app-service-connection'

# - task: TerraformTaskV2@2
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     environmentServiceNameAzureRM: 'youtube-app-service-connection'
